train_dataset: mini-imagenet
train_dataset_args: {split: train}  # outer look not need for resize augment
val_dataset: mini-imagenet
val_dataset_args: {split: val}
tval_dataset: mini-imagenet
tval_dataset_args: {split: test}

model: adapt
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: {n_classes: 64}   # num of classes should == n_way
    meta_train: True
    meta_train_args: {learn_thresh: True, thresh: 0.0, learn_temp: False, temp: 2.0, learn_tp: False}

load_encoder: ./save/classifier_mini-imagenet_resnet12/epoch-last.pth

n_way: 5
n_shot: 5
n_query: 15
train_batches: 200
ep_per_batch: 1

max_epoch: 3   # max epoch for meta train
optimizer: sgd
optimizer_args: {lr: 0.01, weight_decay: 5.e-4}


visualize_datasets: False
