train_dataset: mini-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: mini-imagenet
val_dataset_args: {split: train_phase_val}
fs_dataset: mini-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {aux: True}
    classifier: linear-classifier 
    classifier_args: {n_classes: 64}
    meta_train: False
    meta_train_args: {}

aux_weight: 0.5
batch_size: 128
max_epoch: 150
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [90]}

save_epoch: 10
visualize_datasets: true
